# Generated by Django 4.2 on 2025-12-04 07:36

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("nickname", models.CharField(max_length=50, unique=True)),
                ("apti_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Boat",
            fields=[
                ("boat_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("port", models.CharField(max_length=100)),
                ("contact", models.CharField(blank=True, max_length=50)),
                ("target_fish", models.CharField(max_length=100)),
                ("booking_url", models.URLField()),
                ("source_site", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "boats",
            },
        ),
        migrations.CreateModel(
            name="Buoy",
            fields=[
                (
                    "station_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Diary",
            fields=[
                ("diary_id", models.AutoField(primary_key=True, serialize=False)),
                ("fishing_date", models.DateTimeField()),
                ("location", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "boat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.boat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Egi",
            fields=[
                ("egi_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=50)),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="FishingInsight",
            fields=[
                ("insight_id", models.AutoField(primary_key=True, serialize=False)),
                ("youtube_url", models.URLField()),
                ("situation_text", models.TextField()),
                ("advice_text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                ("weather_id", models.AutoField(primary_key=True, serialize=False)),
                ("temperature", models.FloatField(null=True)),
                ("water_temp", models.FloatField(null=True)),
                ("tide", models.CharField(blank=True, max_length=50)),
                ("wind_speed", models.FloatField(null=True)),
                ("wave_height", models.FloatField(null=True)),
                ("weather_status", models.CharField(blank=True, max_length=50)),
                (
                    "diary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather",
                        to="core.diary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EgiCondition",
            fields=[
                ("condition_id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                (
                    "egi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="core.egi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiaryUsedEgi",
            fields=[
                ("used_id", models.AutoField(primary_key=True, serialize=False)),
                ("color_name", models.CharField(max_length=50)),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_egis",
                        to="core.diary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiaryImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_url", models.URLField()),
                ("is_main", models.BooleanField(default=False)),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.diary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiaryCatch",
            fields=[
                ("catch_id", models.AutoField(primary_key=True, serialize=False)),
                ("fish_name", models.CharField(max_length=50)),
                ("count", models.IntegerField(default=0)),
                ("size", models.FloatField(blank=True, null=True)),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catches",
                        to="core.diary",
                    ),
                ),
            ],
        ),
    ]
