# Generated by Django 4.2 on 2025-12-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryimage",
            name="image_url",
            field=models.ImageField(upload_to="diary_images/"),
        ),
    ]
