# Generated by Django 4.2 on 2025-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_diaryimage_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoastalPoint",
            fields=[
                ("point_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=20)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("nx", models.IntegerField()),
                ("ny", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "coastal_points",
            },
        ),
        migrations.AddIndex(
            model_name="coastalpoint",
            index=models.Index(
                fields=["lat", "lon"], name="coastal_poi_lat_90df20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coastalpoint",
            index=models.Index(fields=["region"], name="coastal_poi_region_32969f_idx"),
        ),
    ]
