# Generated by Django 4.2 on 2025-12-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fishingspot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishingspot",
            name="bottom_type",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="fishingspot",
            name="depth",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="fishingspot",
            name="target_fish",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="fishingspot",
            name="tide",
            field=models.TextField(blank=True),
        ),
    ]
