# Generated by Django 4.2 on 2025-12-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_fishingspot_bottom_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TideStation",
            fields=[
                (
                    "station_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("last_obs_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tide_stations",
            },
        ),
    ]
