# Generated by Django 4.2 on 2025-12-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_egicondition_type_remove_egicondition_value_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE egi
                    DROP COLUMN best_water_color,
                    DROP COLUMN min_water_temp,
                    DROP COLUMN max_water_temp,
                    DROP COLUMN min_wave_height,
                    DROP COLUMN max_wave_height,
                    DROP COLUMN min_wind_speed,
                    DROP COLUMN max_wind_speed,
                    DROP COLUMN weather,
                    DROP COLUMN tide_level,
                    DROP COLUMN notes,
                    DROP COLUMN embedding_text,
                    DROP COLUMN egi_type,
                    DROP COLUMN target_fish;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
