# Generated by Django 4.2 on 2025-12-10 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_egicondition_type_remove_egicondition_value_and_more"),
    ]

    operations = []
