# Generated by Django 4.2 on 2025-12-17 02:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_lat_dms_fishingspot_area_sea_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EgiColor",
            fields=[
                ("color_id", models.AutoField(primary_key=True, serialize=False)),
                ("color_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "egi_colors",
            },
        ),
        migrations.RenameField(
            model_name="weathersnapshot",
            old_name="tide",
            new_name="moon_phase",
        ),
        migrations.RemoveField(
            model_name="diary",
            name="boat",
        ),
        migrations.RemoveField(
            model_name="diary",
            name="location",
        ),
        migrations.RemoveField(
            model_name="egi",
            name="color",
        ),
        migrations.AddField(
            model_name="diary",
            name="boat_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="diary",
            name="lat",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="location_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="diary",
            name="lon",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="stt_provider",
            field=models.CharField(blank=True, default="mock", max_length=30),
        ),
        migrations.AddField(
            model_name="diary",
            name="stt_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="diary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="weathersnapshot",
            name="current_speed",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="weathersnapshot",
            name="wind_direction_deg",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="diary",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="diary",
            name="fishing_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="egi",
            name="color_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.egicolor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diaryusedegi",
            name="color_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.egicolor"
            ),
        ),
    ]
