# Generated by Django 4.2 on 2025-12-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_egicolor_rename_tide_weathersnapshot_moon_phase_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="egi",
            old_name="color_id",
            new_name="color",
        ),
    ]
