# Generated by Django 4.2 on 2025-12-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_rename_color_id_egi_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port_name", models.CharField(max_length=100, verbose_name="어항명")),
                ("address", models.CharField(max_length=255, verbose_name="주소")),
                ("lat", models.FloatField(verbose_name="위도")),
                ("lon", models.FloatField(verbose_name="경도")),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
            ],
            options={
                "db_table": "ports",
            },
        ),
    ]
