# Generated by Django 4.2 on 2025-12-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_port"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diarycatch",
            name="size",
        ),
    ]
