# Generated by Django 4.2 on 2025-12-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_diary_lat_alter_diary_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="weathersnapshot",
            name="wind_direction_16",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
