# Generated by Django 4.2 on 2025-12-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_weathersnapshot_wind_direction_16"),
    ]

    operations = [
        migrations.AddField(
            model_name="weathersnapshot",
            name="rain_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
