# Generated by Django 4.2 on 2025-12-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_weathersnapshot_rain_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="intro_memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boat",
            name="main_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
