# Generated by Django 4.2 on 2025-12-19 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_boat_intro_memo_boat_main_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoatLike",
            fields=[
                ("like_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "boat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="core.boat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boat_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "boat_likes",
            },
        ),
        migrations.AddIndex(
            model_name="boatlike",
            index=models.Index(
                fields=["user", "created_at"], name="boat_likes_user_id_e74b60_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boatlike",
            unique_together={("user", "boat")},
        ),
    ]
