# Generated by Django 4.2 on 2025-12-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_boatlike_boatlike_boat_likes_user_id_e74b60_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileCharacter",
            fields=[
                ("character_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("image_url", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "profile_characters",
                "ordering": ["order", "character_id"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="profile_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.profilecharacter",
            ),
        ),
    ]
