openapi: 3.0.3
info:
  title: Navis Fishing Assistant API
  version: 1.0.0
  description: 낚시 도우미 어플 (용왕의 한 수) API 문서
paths:
  /api/analyze/color/:
    post:
      operationId: analyze_color_create
      description: 물색 분석 Mock API (단독 테스트용)
      tags:
      - analyze
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EgiRecommend'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EgiRecommend'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EgiRecommend'
          description: ''
  /api/auth/login/:
    post:
      operationId: auth_login_create
      description: username과 password로 로그인하고, 유효하면 토큰을 반환합니다.
      summary: 로그인
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: 로그인 성공
        '400':
          description: 입력 오류 / 인증 실패
  /api/auth/me/:
    get:
      operationId: auth_me_retrieve
      description: 현재 토큰으로 인증된 사용자의 기본 정보를 반환합니다.
      summary: 내 정보 조회
      tags:
      - auth
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '401':
          description: 인증 필요 / 토큰 없음
  /api/auth/signup/:
    post:
      operationId: auth_signup_create
      description: username, nickname, email, password를 입력받아 회원가입을 처리하고, 토큰을 발급합니다.
      summary: 회원가입
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Signup'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Signup'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Signup'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Signup'
          description: 회원 생성 성공
        '400':
          description: 유효성 검사 실패
  /api/boats/{boat_id}/schedules/:
    get:
      operationId: boats_schedules_retrieve
      description: 특정 보트의 기간별(기본 7일) 스케줄 조회
      parameters:
      - in: path
        name: boat_id
        schema:
          type: integer
        required: true
      - in: query
        name: date
        schema:
          type: string
          format: date
        description: '기준 날짜 (YYYY-MM-DD, 기본: 오늘)'
      - in: query
        name: days
        schema:
          type: integer
        description: 조회 일수 (기본 7, 최대 14)
      tags:
      - boats
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/boats/search/:
    get:
      operationId: boats_search_retrieve
      description: 보트 검색 + 보트별 가장 가까운 예약 가능 스케줄 1건 요약
      parameters:
      - in: query
        name: area_main
        schema:
          type: string
        description: '광역 지역 (예: 경남, 전남, 제주 등)'
      - in: query
        name: area_sea
        schema:
          type: string
        description: '해역 (예: 동해안, 서해안, 남해안, 제주도, 기타)'
      - in: query
        name: area_sub
        schema:
          type: string
        description: '세부 지역 (예: 통영, 완도, 제주시 등)'
      - in: query
        name: date
        schema:
          type: string
          format: date
        description: '기준 날짜 (YYYY-MM-DD, 기본: 오늘). 이 날짜 기준 7일 내 스케줄 검색'
      - in: query
        name: fish
        schema:
          type: string
        description: '타겟 어종 (부분 검색, 예: 주꾸미, 갑오징어, 시즌어종 등)'
      - in: query
        name: page
        schema:
          type: integer
        description: 페이지 번호(1부터, 기본 1)
      - in: query
        name: page_size
        schema:
          type: integer
        description: 페이지 크기(기본 10, 최대 30)
      tags:
      - boats
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/diaries/:
    get:
      operationId: diaries_list
      description: 낚시 일지 목록 조회/생성 API
      tags:
      - diaries
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Diary'
          description: ''
    post:
      operationId: diaries_create
      description: 낚시 일지 목록 조회/생성 API
      tags:
      - diaries
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Diary'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Diary'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Diary'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diary'
          description: ''
  /api/egi/recommend/:
    post:
      operationId: egi_recommend_create
      description: |-
        Request (multipart/form-data):
          - image: 파일 (물색 사진)
          - lat: float
          - lon: float
          - target_fish: str (옵션, 쭈꾸미/갑오징어/쭈갑, 기본 쭈갑)
          - requested_at: datetime (옵션, ISO 8601)

        Response (JSON):

        {
          "status": "success",
          "data": {
            "analysis_result": {
              "water_color": "Muddy",
              "confidence": 95.5
            },
            "environment": { ... collect_all_marine_data 기반 ... },
            "recommendations": [
              {
                "rank": 1,
                "name": "에기 이름",
                "brand": "브랜드",
                "image_url": "https://.../egi_image/10.jpg",
                "score": 90,
                "reason": "이유 설명..."
              },
              ...
            ]
          }
        }
      tags:
      - egi
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EgiRecommend'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EgiRecommend'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EgiRecommend'
          description: ''
  /api/ocean/:
    get:
      operationId: ocean_retrieve
      description: |-
        사용자 위치(lat, lon)와 대상 어종(target_fish)을 기반으로
        - 해양수산부 바다낚시지수 API
        - 해양관측부이 최신 관측 데이터
        - 기상청 초단기실황 API
        - 조석(물때) API
        를 통합한 환경 정보를 반환합니다.

        target_fish를 생략하면 기본값으로 '쭈갑'(쭈꾸미+갑오징어) 이 사용됩니다.
      summary: 통합 해양/기상 데이터 조회
      parameters:
      - in: query
        name: lat
        schema:
          type: number
          format: float
        description: '사용자 위치 위도 (예: 35.1)'
        required: true
      - in: query
        name: lon
        schema:
          type: number
          format: float
        description: '사용자 위치 경도 (예: 129.0)'
        required: true
      - in: query
        name: target_fish
        schema:
          type: string
        description: 대상 어종 (쭈꾸미, 갑오징어, 쭈갑). 미입력 시 기본값 '쭈갑'
      tags:
      - ocean
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
              examples:
                성공응답예시:
                  value:
                    source: 바다낚시지수 API
                    location_name: 문갑도·선갑도
                    target_fish: 쭈꾸미
                    water_temp: 11.7
                    wave_height: 0.3
                    wind_speed: 2.3
                    current_speed: 2.2
                    fishing_index: 보통
                    fishing_score: 62.59
                    air_temp: 6.9
                    humidity: 51.0
                    rain_type: 0
                    record_time: 2025-12-09 오전
                    moon_phase: 4물
                    next_high_tide: '20:04'
                    next_low_tide: '13:36'
                    tide_station: 덕적도
                    wind_direction_deg: 49.0
                    wind_direction_16: NE
                  summary: 성공 응답 예시
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Diary:
      type: object
      properties:
        diary_id:
          type: integer
          readOnly: true
        date:
          type: string
          readOnly: true
        location:
          type: string
          maxLength: 100
        fishCount:
          type: integer
          readOnly: true
        species:
          type: string
          readOnly: true
        content:
          type: string
        images:
          type: array
          items:
            type: string
            format: uri
          readOnly: true
      required:
      - date
      - diary_id
      - fishCount
      - images
      - location
      - species
    EgiRecommend:
      type: object
      description: |-
        에기 추천 요청용 Serializer

        - image: 물 색 사진
        - lat, lon: 사용자 위치
        - target_fish: 쭈꾸미 / 갑오징어 / 쭈갑 (미선택시 쭈갑)
        - requested_at: 요청 시각 (옵션, 없으면 서버 현재 시각 사용)
      properties:
        image:
          type: string
          format: uri
          description: 물색 분석을 위한 바다 사진
        lat:
          type: number
          format: double
          description: 위도
        lon:
          type: number
          format: double
          description: 경도
        target_fish:
          type: string
          description: 대상 어종 (쭈꾸미 / 갑오징어 / 쭈갑), 미선택시 기본 쭈갑
        requested_at:
          type: string
          format: date-time
          nullable: true
          description: 요청 시각 (ISO 8601, 미전송 시 서버 시간이 사용됨)
      required:
      - image
      - lat
      - lon
    Login:
      type: object
      description: |-
        로그인용 Serializer
        username + password 조합으로 로그인
      properties:
        username:
          type: string
        password:
          type: string
          writeOnly: true
      required:
      - password
      - username
    Signup:
      type: object
      description: |-
        회원가입용 Serializer
        username, password, nickname, email 을 입력받아 User 생성
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        nickname:
          type: string
          maxLength: 50
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
          minLength: 8
        password2:
          type: string
          writeOnly: true
          description: 비밀번호 확인
          minLength: 8
      required:
      - nickname
      - password
      - password2
      - username
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
