# Generated by Django 4.2 on 2026-01-05 03:38

import core.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("nickname", models.CharField(max_length=50, unique=True)),
                ("apti_type", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Boat",
            fields=[
                ("boat_id", models.AutoField(primary_key=True, serialize=False)),
                ("ship_no", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("port", models.CharField(max_length=100)),
                (
                    "main_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("intro_memo", models.TextField(blank=True, null=True)),
                ("area_main", models.CharField(max_length=100)),
                ("area_sub", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("area_sea", models.CharField(max_length=50)),
                ("contact", models.CharField(blank=True, max_length=50)),
                ("target_fish", models.CharField(max_length=100)),
                ("booking_url", models.URLField()),
                ("source_site", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "boats",
            },
        ),
        migrations.CreateModel(
            name="BoatLike",
            fields=[
                ("like_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "boat_likes",
            },
        ),
        migrations.CreateModel(
            name="Buoy",
            fields=[
                (
                    "station_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CoastalPoint",
            fields=[
                ("point_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=20)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("nx", models.IntegerField()),
                ("ny", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "coastal_points",
            },
        ),
        migrations.CreateModel(
            name="Diary",
            fields=[
                ("diary_id", models.AutoField(primary_key=True, serialize=False)),
                ("boat_name", models.CharField(blank=True, default="", max_length=100)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "fishing_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("stt_text", models.TextField(blank=True, default="")),
                (
                    "stt_provider",
                    models.CharField(blank=True, default="mock", max_length=30),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EgiColor",
            fields=[
                ("color_id", models.AutoField(primary_key=True, serialize=False)),
                ("color_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "egi_colors",
            },
        ),
        migrations.CreateModel(
            name="FishingSpot",
            fields=[
                ("spot_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("detail_name", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("area_main", models.CharField(blank=True, max_length=100)),
                ("area_sub", models.CharField(blank=True, max_length=100)),
                ("area_sea", models.CharField(blank=True, max_length=50)),
                ("depth", models.TextField(blank=True)),
                ("bottom_type", models.TextField(blank=True)),
                ("tide", models.TextField(blank=True)),
                ("target_fish", models.TextField(blank=True)),
                ("method", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port_name", models.CharField(max_length=100, verbose_name="어항명")),
                ("address", models.CharField(max_length=255, verbose_name="주소")),
                ("lat", models.FloatField(verbose_name="위도")),
                ("lon", models.FloatField(verbose_name="경도")),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
            ],
            options={
                "db_table": "ports",
            },
        ),
        migrations.CreateModel(
            name="ProfileCharacter",
            fields=[
                ("character_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("image_url", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "profile_characters",
                "ordering": ["order", "character_id"],
            },
        ),
        migrations.CreateModel(
            name="TideStation",
            fields=[
                (
                    "station_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("last_obs_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tide_stations",
            },
        ),
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                ("weather_id", models.AutoField(primary_key=True, serialize=False)),
                ("temperature", models.FloatField(null=True)),
                ("water_temp", models.FloatField(null=True)),
                ("moon_phase", models.CharField(blank=True, max_length=50)),
                ("wind_speed", models.FloatField(null=True)),
                ("wind_direction_deg", models.CharField(max_length=30, null=True)),
                ("wind_direction_16", models.CharField(blank=True, max_length=30)),
                ("wave_height", models.FloatField(null=True)),
                ("current_speed", models.FloatField(null=True)),
                ("weather_status", models.CharField(blank=True, max_length=50)),
                ("rain_type", models.CharField(blank=True, max_length=50)),
                (
                    "diary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather",
                        to="core.diary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Egi",
            fields=[
                ("egi_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(blank=True, max_length=100)),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="S3에 업로드된 에기 이미지 URL",
                        max_length=500,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50)),
                (
                    "purchase_url",
                    models.URLField(
                        blank=True, help_text="에기 구매 링크(출처)", max_length=1000
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.egicolor"
                    ),
                ),
            ],
            options={
                "db_table": "egi",
            },
        ),
        migrations.CreateModel(
            name="DiaryUsedEgi",
            fields=[
                ("used_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "color_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.egicolor"
                    ),
                ),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_egis",
                        to="core.diary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiaryImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image_url",
                    models.ImageField(upload_to=core.models.diary_image_upload_path),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.diary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiaryCatch",
            fields=[
                ("catch_id", models.AutoField(primary_key=True, serialize=False)),
                ("fish_name", models.CharField(max_length=50)),
                ("count", models.IntegerField(default=0)),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catches",
                        to="core.diary",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="coastalpoint",
            index=models.Index(
                fields=["lat", "lon"], name="coastal_poi_lat_90df20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coastalpoint",
            index=models.Index(fields=["region"], name="coastal_poi_region_32969f_idx"),
        ),
        migrations.AddField(
            model_name="boatlike",
            name="boat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="core.boat",
            ),
        ),
        migrations.AddField(
            model_name="boatlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boat_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="boat",
            index=models.Index(fields=["ship_no"], name="boats_ship_no_ae0fa8_idx"),
        ),
        migrations.AddIndex(
            model_name="boat",
            index=models.Index(
                fields=["area_main", "area_sub"], name="boats_area_ma_8d2776_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boat",
            index=models.Index(fields=["area_sea"], name="boats_area_se_045f10_idx"),
        ),
        migrations.AddIndex(
            model_name="boat",
            index=models.Index(fields=["target_fish"], name="boats_target__ec324d_idx"),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.profilecharacter",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="boatlike",
            index=models.Index(
                fields=["user", "created_at"], name="boat_likes_user_id_e74b60_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boatlike",
            unique_together={("user", "boat")},
        ),
    ]
