# Generated by Django 4.2 on 2025-12-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_coastalpoint_coastalpoint_coastal_poi_lat_90df20_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FishingSpot",
            fields=[
                ("spot_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("detail_name", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("lat_dms", models.CharField(blank=True, max_length=50)),
                ("lon_dms", models.CharField(blank=True, max_length=50)),
                ("depth", models.CharField(blank=True, max_length=50)),
                ("bottom_type", models.CharField(blank=True, max_length=50)),
                ("tide", models.CharField(blank=True, max_length=50)),
                ("target_fish", models.CharField(blank=True, max_length=100)),
                ("method", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
