# Generated by Django 4.2 on 2025-12-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_tidestation"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="egicondition",
        #     name="type",
        # ),
        # migrations.RemoveField(
        #     model_name="egicondition",
        #     name="value",
        # ),
        migrations.AddField(
            model_name="egicondition",
            name="catch_score",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="embedding_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="max_water_temp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="max_wave_height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="max_wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="min_water_temp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="min_wave_height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="min_wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="season",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="target_fish",
            field=models.CharField(
                choices=[
                    ("쭈꾸미", "쭈꾸미"),
                    ("갑오징어", "갑오징어"),
                    ("쭈갑", "쭈갑"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="egicondition",
            name="tide_level",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="time_of_day",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="water_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VeryClear", "VeryClear"),
                    ("Clear", "Clear"),
                    ("Moderate", "Moderate"),
                    ("Muddy", "Muddy"),
                    ("VeryMuddy", "VeryMuddy"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="egicondition",
            name="weather",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="egi",
            name="brand",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="egi",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="S3에 업로드된 에기 이미지 URL", max_length=500
            ),
        ),
        migrations.AlterModelTable(
            name="egi",
            table="egi",
        ),
        migrations.AlterModelTable(
            name="egicondition",
            table="egi_conditions",
        ),
    ]
