# Generated by Django 4.2 on 2025-12-10 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_egicondition_type_remove_egicondition_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="egicondition",
            name="type",
        ),
        migrations.RemoveField(
            model_name="egicondition",
            name="value",
        ),
        migrations.AddField(
            model_name="boat",
            name="ship_no",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="egi",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="egi",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="egi",
            name="size",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
