# Generated by Django 4.2 on 2025-12-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_egicondition_type_remove_egicondition_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="boat",
            name="area_main",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="boat",
            name="area_sea",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="boat",
            name="area_sub",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
