# Generated by Django 4.2 on 2025-12-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_boat_address_boat_area_main_boat_area_sea_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fishingspot",
            old_name="lat_dms",
            new_name="area_sea",
        ),
        migrations.RemoveField(
            model_name="fishingspot",
            name="lon_dms",
        ),
        migrations.AddField(
            model_name="fishingspot",
            name="area_main",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="fishingspot",
            name="area_sub",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="boat",
            index=models.Index(fields=["ship_no"], name="boats_ship_no_ae0fa8_idx"),
        ),
        migrations.AddIndex(
            model_name="boat",
            index=models.Index(
                fields=["area_main", "area_sub"], name="boats_area_ma_8d2776_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boat",
            index=models.Index(fields=["area_sea"], name="boats_area_se_045f10_idx"),
        ),
        migrations.AddIndex(
            model_name="boat",
            index=models.Index(fields=["target_fish"], name="boats_target__ec324d_idx"),
        ),
    ]
