# Generated by Django 4.2 on 2025-12-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_diarycatch_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diary",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
