# Generated by Django 4.2 on 2025-12-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_profilecharacter_user_profile_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="egi",
            name="purchase_url",
            field=models.URLField(
                blank=True, help_text="에기 구매 링크(출처)", max_length=1000
            ),
        ),
    ]
