# Generated by Django 4.2 on 2025-12-31 06:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_egi_purchase_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryimage",
            name="image_url",
            field=models.ImageField(upload_to=core.models.diary_image_upload_path),
        ),
        migrations.DeleteModel(
            name="EgiCondition",
        ),
    ]
